name:                haskell-second-lab
version:             0.1.0.0
github:              "deffrian/haskell-first-lab"
license:             BSD3
author:              "Mescheryakov Nikita"
maintainer:          "hunter181999@gmail.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deffrian/haskell-second-lab#readme>

dependencies:
- base >= 4.7 && < 5
- array == 0.5.4.0
- mtl == 2.2.2
- hspec == 2.7.4
- aeson
- servant-server
- servant-client
- http-client
- wai
- warp
- http-api-data
- hashable
- ctrie
- atomic-primops
- brick
- vty


library:
  source-dirs: src

executables:
  haskell-second-lab-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-second-lab

tests:
  haskell-second-lab-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-second-lab
